package org.egov.bpa.web.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum BuildingPermitAuthorityEnum {

    // Existing entries
    MB("MUNICIPAL_BOARD"),
    GP("GAON_PANCHAYAT"),
    GMC("GUWAHATI_MUNICIPAL_CORPORATION"),
    NGMB("NORTH_GUWAHATI_MUNICIPAL_BOARD"),

    // Nalbari
    NALBARI_MB("NALBARI_MB"),
    PUB_BAHJANI("PUB_BAHJANI"),
    BALITARA_BATAHGILA("BALITARA_BATAHGILA"),
    SARIATOLI("SARIATOLI"),
    CHANDAKUCHI("CHANDAKUCHI"),
    UTTAR_PUB_DHARMAPUR("UTTAR_PUB_DHARMAPUR"),
    MADHYA_BAHJANI("MADHYA_BAHJANI"),
    HATI_NAMATI("HATI_NAMATI"),
    DAKSHIN_NALBARI("DAKSHIN_NALBARI"),
    UTTAR_PUB_KHATA("UTTAR_PUB_KHATA"),
    PUB_NALBARI("PUB_NALBARI"),
    UPPER_BARBHAG_KHATA("UPPER_BARBHAG_KHATA"),
    DIGHELI("DIGHELI"),
    NATUN_DEHAR("NATUN_DEHAR"),
    PANIGAON("PANIGAON"),
    GHOGRAPAR("GHOGRAPAR"),
    SILPOTABORI_LATIMA("SILPOTABORI_LATIMA"),
    BARAJOL("BARAJOL"),
    DIHJARI("DIHJARI"),

    // Barpeta
    BARPETA_MB("BARPETA_MB"),
    PATBAUSHI("PATBAUSHI"),
    SUNDARIDIA("SUNDARIDIA"),

    // Dibrugarh
    DIBRUGARH_MC("DIBRUGARH_MC"),
    RAJABHETA("RAJABHETA"),
    NIZ_MANKOTTA("NIZ_MANKOTTA"),
    HILOIDHARI("HILOIDHARI"),
    MANKOTTA_KHANIKAR("MANKOTTA_KHANIKAR"),
    ROMAI("ROMAI"),
    TIMONA("TIMONA"),
    MOHANBARI("MOHANBARI"),
    BOKUL("BOKUL"),
    MAIJAN("MAIJAN"),
    NIZ_KANAI("NIZ_KANAI"),
    MODERKHAT("MODERKHAT"),
    LAHOWAL("LAHOWAL"),
    KOTOHA("KOTOHA"),
    BORPOTHAR("BORPOTHAR"),
    JOKAI("JOKAI"),
    LEJAI("LEJAI"),
    BARBARUA("BARBARUA"),
    DULIA_KAKOTI("DULIA_KAKOTI"),
    KALAKHOWA("KALAKHOWA"),
    GARUDHORIA("GARUDHORIA"),
    BOGIBEEL("BOGIBEEL"),

    // Tinsukia
    TINSUKIA_MB("TINSUKIA_MB"),
    RONGPURIA("RONGPURIA"),
    BORGURI("BORGURI"),
    BOJALTOLI("BOJALTOLI"),
    ITAKHULI_CHARIALI("ITAKHULI_CHARIALI"),
    LAIPULI("LAIPULI"),
    DIMARUGURI("DIMARUGURI"),
    BAPUJI("BAPUJI"),
    GOTTONG("GOTTONG"),
    PANITOLA("PANITOLA"),
    BAREKURI("BAREKURI"),
    HAPJAN("HAPJAN"),
    JERAI("JERAI"),
    TENGAPANI("TENGAPANI"),

    // Silchar
    SILCHAR_MC("SILCHAR_MC"),
    MADHUR_BOND("MADHUR_BOND"),
    BERENGA("BERENGA"),
    BHAGADHAR_BARJURAI("BHAGADHAR_BARJURAI"),
    AMBIKAPUR("AMBIKAPUR"),
    GHUNGOOR("GHUNGOOR"), // Keep one version
    BHANJANTIPUR("BHANJANTIPUR"),
    MEHERPUR("MEHERPUR"),
    KANAKPUR("KANAKPUR"),
    RONGPUR("RONGPUR"),
    UTTAR_KRISHNAPUR("UTTAR_KRISHNAPUR"),
    DAKSHIN_KRISHNAPUR("DAKSHIN_KRISHNAPUR"),
    TUPKHANA("TUPKHANA"),
    GHOUNGOOR("GHOUNGOOR"), // Keep one version
    BHORAKHAI("BHORAKHAI"),
    TARUTAJABARI("TARUTAJABARI"),
    CHENKOORI("CHENKOORI"),
    RAJNAGAR("RAJNAGAR"),
    KUMARPARA_NIZJOINAGAR("KUMARPARA_NIZJOINAGAR");

    private final String value;
}
